"""empty message

Revision ID: 6ebb1345afb0
Revises: 878e1122f561
Create Date: 2020-06-06 19:27:28.991122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebb1345afb0'
down_revision = '878e1122f561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('alt', sa.String(length=200), nullable=True))
    op.add_column('media', sa.Column('full_jpeg', sa.String(length=200), nullable=False))
    op.add_column('media', sa.Column('large_jpeg', sa.String(length=200), nullable=False))
    op.add_column('media', sa.Column('med_jpeg', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'med_jpeg')
    op.drop_column('media', 'large_jpeg')
    op.drop_column('media', 'full_jpeg')
    op.drop_column('media', 'alt')
    # ### end Alembic commands ###
