"""empty message

Revision ID: 88b1cde4e4d7
Revises: 6ebb1345afb0
Create Date: 2020-06-06 19:50:15.670386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88b1cde4e4d7'
down_revision = '6ebb1345afb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'large',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('media', 'large_jpeg',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('media', 'med',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('media', 'med_jpeg',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'med_jpeg',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('media', 'med',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('media', 'large_jpeg',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('media', 'large',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
