"""projects

Revision ID: 9f181aa19a19
Revises: 
Create Date: 2019-09-05 09:15:33.301508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f181aa19a19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('tech', sa.String(length=512), nullable=True),
    sa.Column('thumb_img', sa.String(length=1024), nullable=True),
    sa.Column('featured_img', sa.String(length=1024), nullable=True),
    sa.Column('project_url', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(length=65535), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_project_slug'), 'project', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_slug'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
