"""empty message

Revision ID: b93ce23883ce
Revises: 88b1cde4e4d7
Create Date: 2020-06-23 10:36:48.690237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93ce23883ce'
down_revision = '88b1cde4e4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('slug', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'slug')
    # ### end Alembic commands ###
