"""empty message

Revision ID: c049cdf922e1
Revises: b93ce23883ce
Create Date: 2020-06-23 11:10:16.529283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c049cdf922e1'
down_revision = 'b93ce23883ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'site', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='unique')
    # ### end Alembic commands ###
